/** @format */

const vehicles = [
  {
    id: "1",
    uri: require("../../../assets/images/xe_1.png"),
    name: "VinFast VF 8 Plus",
    star: 4.5,
    price: "1.057.100.000",
    status: "New",
  },
  {
    id: "2",
    uri: require("../../../assets/images/xe_3.png"),
    name: "VinFast VF 5 Plus",
    star: 4.5,
    price: "538.000.000",
    status: "New",
  },
  {
    id: "3",
    uri: require("../../../assets/images/xe_4.png"),
    name: "VinFast VF 8 Plus",
    star: 4.5,
    price: "900.000.000",
    status: "New",
  },
  {
    id: "4",
    uri: require("../../../assets/images/xe_2.png"),
    name: "VinFast FELIZ S",
    star: 4.5,
    price: "29.900.000",
    status: "New",
  },
  {
    id: "5",
    uri: require("../../../assets/images/xe_5.png"),
    name: "VinFast KLARA A2",
    star: 4.5,
    price: "26.900.000",
    status: "New",
  },
  {
    id: "6",
    uri: require("../../../assets/images/xe_1.png"),
    name: "VinFast VF 8 Plus",
    star: 4.5,
    price: "1.057.100.000",
    status: "New",
  },
  {
    id: "7",
    uri: require("../../../assets/images/xe_3.png"),
    name: "VinFast VF 5 Plus",
    star: 4.5,
    price: "538.000.000",
    status: "New",
  },
  {
    id: "8",
    uri: require("../../../assets/images/xe_4.png"),
    name: "VinFast VF 8 Plus",
    star: 4.5,
    price: "900.000.000",
    status: "New",
  },
  {
    id: "9",
    uri: require("../../../assets/images/xe_2.png"),
    name: "VinFast FELIZ S",
    star: 4.5,
    price: "29.900.000",
    status: "New",
  },
  {
    id: "10",
    uri: require("../../../assets/images/xe_5.png"),
    name: "VinFast KLARA A2",
    star: 4.5,
    price: "26.900.000",
    status: "New",
  },
];
export default vehicles;
